version: '3.8'

services:
  app:
    container_name: jgts-music
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    environment:
      - PORT=4001
    volumes:
      - .:/app

      
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db


