version: '3.8'

services:
  app:
    container_name: jgts-music
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    volumes:
      - .:/app